# Transformación de Datos y Pipeline

En esta sección se realiza la transformación del dataset limpio, incluyendo:
- Escalado de variables numéricas
- Codificación de variables categóricas
- Construcción de un pipeline para automatizar el proceso

In [ ]:
import pandas as pd

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [ ]:
url = "https://raw.githubusercontent.com/Nicossm/parcial1/main/data/processed/clean.csv"
df = pd.read_csv(url)

display(df)

,experience,country,education,languages,frameworks,company_size,salary_usd,salary_usd_before_cap
0,24,India,Bachelors,"Go, Ruby","Django, Flask",5000+,122189.0,122189.0
1,38,France,Masters,"Python, Ruby",Unknown,201-1000,147754.0,147754.0
2,36,USA,Some College,"C++, PHP","Ruby on Rails, Spring",5000+,220819.0,220819.0
3,3,India,Masters,"Java, JavaScript","Ruby on Rails, Spring",1-10,31943.0,31943.0
4,18,USA,Masters,"Go, Java","Django, React",5000+,166442.0,166442.0
...,...,...,...,...,...,...,...,...
9255,20,France,Bachelors,"Go, Rust","Angular, Express",1-10,154727.0,154727.0
9256,5,Japan,Masters,Unknown,"Laravel, Vue",1001-5000,69876.0,69876.0
9257,21,USA,Unknown,"Python, Swift","Django, Express",11-50,154794.0,154794.0
9258,37,USA,Masters,"C#, Swift","Angular, Laravel",51-200,178945.0,178945.0
9259,34,France,Bachelors,"C#, C++","ASP.NET, Laravel",1-10,170249.0,170249.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9260 entries, 0 to 9259
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   experience             9260 non-null   int64
 1   country                9260 non-null   object
 2   education              9260 non-null   object
 3   languages              9260 non-null   object
 4   frameworks             9260 non-null   object
 5   company_size           9260 non-null   object
 6   salary_usd             9260 non-null   float64
 7   salary_usd_before_cap  9260 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 578.9+ KB

In [ ]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].unique())

country ['India' 'France' 'USA' 'Japan' 'Australia' 'Germany' 'Brazil' 'UK'
 'Canada' 'Singapore' 'Ca' 'U.S.A.' 'Deutschland' 'Gb' 'De' 'In' 'Jp'
 'U.K.' 'Au' 'Sg' 'Br']
education ['Bachelors' 'Masters' 'Some College' 'Unknown' 'High School' 'PhD'
 "Master'S" "Bachelor'S" 'Incomplete' 'Secondary' 'Somecollege'
 'Highschool' 'Doctorate' 'Ph.D.']
languages ['Go, Ruby' 'Python, Ruby' 'C++, PHP' 'Java, JavaScript' 'Go, Java'
 'C++, Python' 'Ruby, Rust' 'C#, Go' 'JavaScript, Python' 'C++, Swift'
 'C++, Rust' 'PHP, Python' 'C#, Swift' 'Go, JavaScript' 'PHP, Rust'
 'JavaScript, PHP' 'PHP, Ruby' 'C++, Java' 'C#, Python' 'Go' 'C++'
 'Unknown' 'Ruby, Swift' 'Go, Swift' 'PHP, Swift' 'C#, JavaScript' 'Swift'
 'C++, Ruby' 'C++, JavaScript' 'Java, Python' 'Python, Swift' 'C#, Java'
 'Java' 'C#' 'C#, Rust' 'C#, PHP' 'Go, PHP' 'JavaScript' 'Rust, Swift'
 'JavaScript, Swift' 'JavaScript, Rust' 'C#, Ruby' 'Java, Ruby'
 'Java, Swift' 'Java, Rust' 'JavaScript, Ruby' 'Go, Python' 'C++, Go'
 'Ruby' 'Java, PHP' 'Go, Rust' 'C#, C++' 'Python, Rust' 'Rust' 'Python'
 'PHP']
frameworks ['Django, Flask' 'Unknown' 'Ruby on Rails, Spring' 'Django, React'
 'Ruby on Rails, Vue' 'Spring, Vue' 'Angular, Flask' 'Laravel'
 'Ruby on Rails' 'Express, Vue' 'Laravel, Ruby on Rails' 'Flask, React'
 'Flask' 'React, Ruby on Rails' 'Express, Flask' 'ASP.NET, Spring'
 'Angular, React' 'Django, Vue' 'Angular, Express' 'Laravel, React'
 'React, Vue' 'Laravel, Spring' 'Angular, ASP.NET' 'ASP.NET, Laravel'
 'ASP.NET, Express' 'Django' 'Flask, Ruby on Rails'
 'Angular, Ruby on Rails' 'Angular, Laravel' 'Angular, Spring'
 'Angular, Django' 'Express, Spring' 'ASP.NET, Flask' 'ASP.NET, Vue'
 'React, Spring' 'Angular' 'Spring' 'Flask, Spring' 'Django, Laravel'
 'Express' 'ASP.NET, Django' 'Express, Laravel' 'Django, Ruby on Rails'
 'Angular, Vue' 'Flask, Laravel' 'React' 'ASP.NET, Ruby on Rails'
 'Flask, Vue' 'Django, Express' 'Express, Ruby on Rails' 'Vue'
 'Django, Spring' 'ASP.NET, React' 'Laravel, Vue' 'Express, React'
 'ASP.NET']
company_size ['5000+' '201-1000' '1-10' '51-200' '1001-5000' '11-50']

In [ ]:
df.head(20)

,experience,country,education,languages,frameworks,company_size,salary_usd,salary_usd_before_cap
0,24,India,Bachelors,"Go, Ruby","Django, Flask",5000+,122189.0,122189.0
1,38,France,Masters,"Python, Ruby",Unknown,201-1000,147754.0,147754.0
2,36,USA,Some College,"C++, PHP","Ruby on Rails, Spring",5000+,220819.0,220819.0
3,3,India,Masters,"Java, JavaScript","Ruby on Rails, Spring",1-10,31943.0,31943.0
4,18,USA,Masters,"Go, Java","Django, React",5000+,166442.0,166442.0
5,24,Japan,Bachelors,"C++, Python","Ruby on Rails, Vue",1-10,121414.0,121414.0
6,3,USA,Bachelors,"Ruby, Rust","Spring, Vue",51-200,79820.0,79820.0
7,26,Australia,Masters,"C#, Go","Ruby on Rails, Vue",5000+,170805.0,170805.0
8,17,Germany,Bachelors,"JavaScript, Python","Angular, Flask",1001-5000,113387.0,113387.0
9,30,Brazil,Masters,"C++, Swift",Laravel,51-200,174312.0,174312.0
10,21,UK,Bachelors,"C++, Rust",Ruby on Rails,201-1000,133780.0,133780.0
11,20,UK,Masters,"Java, JavaScript","Express, Vue",1001-5000,106330.0,106330.0
12,5,Australia,Unknown,"C++, Python","Laravel, Ruby on Rails",201-1000,59647.0,59647.0
13,22,USA,Unknown,"PHP, Python","Django, React",51-200,151891.0,151891.0
14,22,Germany,Masters,"C++, Python","Flask, React",5000+,153156.0,153156.0
15,9,USA,Bachelors,"C#, Swift","Spring, Vue",11-50,116804.0,116804.0
16,30,India,High School,"C++, Python",Unknown,201-1000,107637.0,107637.0
17,21,Japan,Unknown,"C++, Rust",Flask,1-10,125214.0,125214.0
18,30,France,Masters,"Go, JavaScript","Express, Vue",1-10,138715.0,138715.0
19,20,USA,Bachelors,"C#, Swift","React, Ruby on Rails",201-1000,231376.0,231376.0